In [2]:
import numpy as np

In [3]:
# must have same data type and the same # of elements
a = np.array([[1,3,5], [0,2,4]])
a

array([[1, 3, 5],
       [0, 2, 4]])

In [4]:
a.shape

(2, 3)

In [5]:
a[0,2]

5

In [6]:
a[0,2]=7
a

array([[1, 3, 7],
       [0, 2, 4]])

In [7]:
b = np.array([[2,4], [6,8], [10,12]])
b

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

## importing random numbers


In [3]:
import random

In [11]:
# random() only between 0-1
prob = random.random()
prob

0.14195966600802779

In [16]:
# randint() generates random numbers between specified interval
number = random.randint(1,8)
number

2

In [14]:
c = np.random.randint(1,6,(1,4))
c

array([[5, 3, 5, 5]])

In [19]:
import pandas as pd 

In [23]:
ser = pd.Series(np.random.random(5), name = "Column 01")
ser

0    0.522845
1    0.775168
2    0.810385
3    0.223453
4    0.029537
Name: Column 01, dtype: float64

In [26]:
from pandas_datareader import data as wb

In [29]:
PG = wb.DataReader("PG", data_source = "yahoo", start = "1995-1-1")
PG

High         Low        Open       Close      Volume  \
Date                                                                     
1995-01-03   15.625000   15.437500   15.468750   15.593750   3318400.0   
1995-01-04   15.656250   15.312500   15.531250   15.468750   2218800.0   
1995-01-05   15.437500   15.218750   15.375000   15.250000   2319600.0   
1995-01-06   15.406250   15.156250   15.156250   15.281250   3438000.0   
1995-01-09   15.406250   15.187500   15.343750   15.218750   1795200.0   
...                ...         ...         ...         ...         ...   
2020-03-23  103.750000   94.339996  100.190002   97.699997  17776800.0   
2020-03-24  104.000000   96.070000  101.230003  103.269997  14625500.0   
2020-03-25  104.699997   98.599998  100.510002  100.919998  13789100.0   
2020-03-26  108.309998  102.529999  103.879997  107.379997  15796000.0   
2020-03-27  114.290001  106.489998  106.489998  110.279999  12210058.0   

             Adj Close  
Date                    
1995-01-03    6.362402  
1995-01-04    6.311406  
1995-01-05    6.222151  
1995-01-06    6.234900  
1995-01-09    6.209402  
...                ...  
2020-03-23   97.699997  
2020-03-24  103.269997  
2020-03-25  100.919998  
2020-03-26  107.379997  
2020-03-27  110.279999  

[6354 rows x 6 columns]

In [30]:
PG.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 6354 entries, 1995-01-03 to 2020-03-27
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   High       6354 non-null   float64
 1   Low        6354 non-null   float64
 2   Open       6354 non-null   float64
 3   Close      6354 non-null   float64
 4   Volume     6354 non-null   float64
 5   Adj Close  6354 non-null   float64
dtypes: float64(6)
memory usage: 347.5 KB


In [31]:
PG.head()

High       Low      Open     Close     Volume  Adj Close
Date                                                                    
1995-01-03  15.62500  15.43750  15.46875  15.59375  3318400.0   6.362402
1995-01-04  15.65625  15.31250  15.53125  15.46875  2218800.0   6.311406
1995-01-05  15.43750  15.21875  15.37500  15.25000  2319600.0   6.222151
1995-01-06  15.40625  15.15625  15.15625  15.28125  3438000.0   6.234900
1995-01-09  15.40625  15.18750  15.34375  15.21875  1795200.0   6.209402

In [32]:
PG.tail()

High         Low        Open       Close      Volume  \
Date                                                                     
2020-03-23  103.750000   94.339996  100.190002   97.699997  17776800.0   
2020-03-24  104.000000   96.070000  101.230003  103.269997  14625500.0   
2020-03-25  104.699997   98.599998  100.510002  100.919998  13789100.0   
2020-03-26  108.309998  102.529999  103.879997  107.379997  15796000.0   
2020-03-27  114.290001  106.489998  106.489998  110.279999  12210058.0   

             Adj Close  
Date                    
2020-03-23   97.699997  
2020-03-24  103.269997  
2020-03-25  100.919998  
2020-03-26  107.379997  
2020-03-27  110.279999

In [35]:
PG.head(10)

High       Low      Open     Close     Volume  Adj Close
Date                                                                    
1995-01-03  15.62500  15.43750  15.46875  15.59375  3318400.0   6.362402
1995-01-04  15.65625  15.31250  15.53125  15.46875  2218800.0   6.311406
1995-01-05  15.43750  15.21875  15.37500  15.25000  2319600.0   6.222151
1995-01-06  15.40625  15.15625  15.15625  15.28125  3438000.0   6.234900
1995-01-09  15.40625  15.18750  15.34375  15.21875  1795200.0   6.209402
1995-01-10  15.43750  15.18750  15.28125  15.40625  4364000.0   6.285902
1995-01-11  15.59375  15.37500  15.59375  15.37500  3738400.0   6.273152
1995-01-12  15.53125  15.31250  15.37500  15.53125  3307600.0   6.336905
1995-01-13  15.84375  15.53125  15.59375  15.62500  3992800.0   6.522133
1995-01-16  15.96875  15.75000  15.90625  15.75000  3677200.0   6.574313

In [38]:
tickers = ['PG', 'MSFT', 'T', 'F', 'GE']
new_data = pd.DataFrame()
for t in tickers:
    new_data[t] = wb.DataReader(t, data_source = 'yahoo', start = '1995-1-1')['Adj Close']

In [39]:
new_data.tail(10) 

PG        MSFT          T     F    GE
Date                                                     
2020-03-16  108.500000  135.419998  31.809999  5.01  6.66
2020-03-17  118.239998  146.570007  33.740002  5.01  7.08
2020-03-18  117.449997  140.399994  32.849998  4.50  6.60
2020-03-19  110.830002  142.710007  31.150000  4.47  6.48
2020-03-20  102.430000  137.350006  28.450001  4.33  6.52
2020-03-23   97.699997  135.979996  26.770000  4.01  6.11
2020-03-24  103.269997  148.339996  28.090000  4.95  7.01
2020-03-25  100.919998  146.919998  28.400000  5.39  7.56
2020-03-26  107.379997  156.110001  30.600000  5.25  8.12
2020-03-27  110.169998  149.699997  29.840000  5.19  7.62

In [41]:
import quandl

In [43]:
mydata_01 = quandl.get('FRED/GDP')

In [45]:
mydata_01.head()

Value
Date               
1947-01-01  243.164
1947-04-01  245.968
1947-07-01  249.585
1947-10-01  259.745
1948-01-01  265.742

In [46]:
# saving the data to specified folder as CSV file
import pandas as pd 

In [50]:
mydata_01.to_csv("C:/Users/nicat/Desktop/Python/Python for Investment/example_01.csv")

In [51]:
# to import the csv data - mydata_02 = pd.read_csv("C:/Users/nicat/Desktop/Python/Python for Investment/example_02.csv")

In [55]:
mydata_01.to_excel("C:/Users/nicat/Desktop/Python/Python for Investment/example_01.xlsx")